services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    env_file:
      - ./server/.env.example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./server/.env.example
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
    networks:
      - mynetwork

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    environment:
      VITE_SERVER_URL: "http://localhost:4000"
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
